% This dictionnary contains the type of every register
%
%
% Note :
% Some registers may change name with futur uptade
% SignalGeneratorMode is not defined in the documenation, it is an enumeration that can take 2 values :
% "On" and "Off"
% 






  registerType = dictionary(...
 "DeviceOperationMode","Enumeration",...
 "ChunkModeActive","Boolean",...
 "ChunkEnable","Boolean",...
 "ChunkSelector","Enumeration",...
 "LockInTargetReferenceFrequency","Float",...
 "LockInReferenceSourceType","Enumeration",...
 "TriggerSelector","Enumeration",...
 "TriggerMode","Enumeration",...
 "TriggerSource","Enumeration",...
 "LockInCoupling","Enumeration",...
 "LockInSensitivity","Float",...
 "LockInTargetTimeConstantNPeriods","Integer",...
 "Scan3dExtractionMethod","Enumeration",...
 "ComponentSelector","Enumeration",...
 "ComponentEnable","Boolean",...
 "AcquisitionBurstFrameCount","Integer",...
 "LightControllerSelector","Enumeration",...
 "LightControllerSource","Enumeration",...
 "SignalGeneratorFrequency","Float",...
 "SignalGeneratorAmplitude","Float",...
 "SignalGeneratorOffset","Float",...
 "SignalGeneratorMode","Enumeration"...
 );
