%%Additional parameters less useful

%%%%%%%%
%%Acquisition parameters
%%%%%%%%
cpanel1_add=uipanel('Parent',tab_additional,'Position',[0.2 0.8 0.12 0.15]);

uicontrol('Parent',tab_additional,'Style', 'checkbox', 'String', 'RandomFreq','units','normalized','tag','RandomFreq',...
    'Position', [0.21 0.833 0.07 0.025],'FontSize',12,'Value',AcqParameters.RandomFreq,'Callback',@UpdateAcqParam);
uicontrol('Parent',tab_additional,'Style', 'checkbox', 'String', 'AutoAlignCrop','units','normalized','tag','AutoAlignCrop',...
    'Position', [0.21 0.893 0.07 0.025],'FontSize',12,'Value',AcqParameters.AutoAlignCrop,'Callback',@UpdateAutoAlignCrop);


%%%%%% Save Mode
% Create the button group
bg_saveMode = uibuttongroup('Parent', tab_additional, 'units', 'normalized', ...
                  'Position', [0.075 0.8 0.12 0.15], 'tag', 'SaveModeChoice', ...
                  'SelectionChangedFcn', @UpdateAcqParam);         

% Create the radio buttons (arranged vertically with closer spacing)
r1_saveMode = uicontrol(bg_saveMode, 'Style', 'radiobutton', 'units', 'normalized', ...
                  'String', 'slow&compressed', 'FontSize', 12, 'tag', 'SaveModeSlow', ...
                  'Position', [0.05 0.6 0.9 0.2], ...
                  'TooltipString', 'Default slow save mode');   

r2_saveMode = uicontrol(bg_saveMode, 'Style', 'radiobutton', 'units', 'normalized', ...
                  'String', 'fast&heavy', 'FontSize', 12, 'tag', 'SaveModeFast', ...
                  'Position', [0.05 0.35 0.9 0.2], ...
                  'TooltipString', 'Fast save mode: 50 times faster, file 3 times bigger');   

r3_saveMode = uicontrol(bg_saveMode, 'Style', 'radiobutton', 'units', 'normalized', ...
                  'String', 'h5', 'FontSize', 12, 'tag', 'SaveModeH5', ...
                  'Position', [0.05 0.1 0.9 0.2], ...
                  'TooltipString', 'Save using HDF5 format');                

% Create a centered label
uicontrol('Parent', bg_saveMode, 'Style', 'text', 'FontSize', 12, 'units', 'normalized', ...
          'Position', [0.05 0.85 0.9 0.15], 'HorizontalAlignment', 'center', ...
          'String', 'Save Mode');

if strcmp(AcqParameters.SaveMode,'fast&heavy')
   bg_saveMode.SelectedObject = r2_saveMode;
elseif strcmp(AcqParameters.SaveMode,'h5')
    bg_saveMode.SelectedObject = r3_saveMode;
else 
   bg_saveMode.SelectedObject = r1_saveMode;
end
