% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% %% Elements of Heliotis Control Tab (tab_helicam)
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% --- Prerequisite: Ensure tab_helicam and global ObjCamera exist and is initialized ---
global ObjCamera

% Initialize ObjCamera if it hasn't been (ensure fields exist)
if isempty(ObjCamera) || ~isstruct(ObjCamera) % Or ~isobject if it's an object
    disp('Initializing global ObjCamera for Heliotis Tab testing...');
    ObjCamera = struct(); % Or your class constructor
end
if ~isfield(ObjCamera, 'NbFrames'), ObjCamera.NbFrames = 100; end
if ~isfield(ObjCamera, 'NPeriods'), ObjCamera.NPeriods = 10; end
if ~isfield(ObjCamera, 'sensitivity'), ObjCamera.sensitivity = 0.5; end
if ~isfield(ObjCamera, 'coupling'), ObjCamera.coupling = 'AC'; end % Default
if ~isfield(ObjCamera, 'refFrequency'), ObjCamera.refFrequency = 5; end % Example frequency in kHz

% --- UI Element Definitions ---
% Store handles to UI elements of this tab if needed for dynamic updates between them
heliHandles = struct(); % To store handles of controls in this tab

labelFontSize = 11;
editFontSize = 11;
uiHeight = 0.04; % Normalized height for rows
vSpacing = 0.01; % Vertical spacing between rows
currentY = 1 - uiHeight - vSpacing*2; % Start from top with a bit more margin

% Define Min/Max for your modulation frequency
modFreqMin = 1;    % kHz
modFreqMax = 10;   % kHz

% Define Min/Max for your Sensitivity
SensitivityMin = 0;    
SensitivityMax = 1;  

% --- 1. Frame Number ---
uicontrol('Parent', tab_helicam, 'Style', 'text', 'String', 'Frame Number', ...
    'units', 'normalized','Position', [0.75 currentY 0.06 uiHeight*0.7], ...
    'HorizontalAlignment', 'left', 'FontSize', labelFontSize);
heliHandles.NbFrames = uicontrol('Parent', tab_helicam, 'Style', 'edit', 'tag', 'NbFrames', ...
    'units', 'normalized', 'Position', [0.82 currentY 0.03 uiHeight*0.8], ...
    'String', num2str(ObjCamera.NbFrames), 'Callback', @setNbFrames, ...
    'FontSize', editFontSize);
currentY = currentY - uiHeight - vSpacing;

% --- 2. Integration Period Numbers ---
uicontrol('Parent', tab_helicam, 'Style', 'text', 'String', 'Integration Periods', ...
    'units', 'normalized', 'Position', [0.75 currentY 0.07 uiHeight*0.7], ...
    'HorizontalAlignment', 'left', 'FontSize', labelFontSize);
heliHandles.NPeriods = uicontrol('Parent', tab_helicam, 'Style', 'edit', 'tag', 'NPeriods', ...
    'units', 'normalized', 'Position', [0.82 currentY 0.03 uiHeight*0.8], ...
    'String', num2str(ObjCamera.NPeriods), 'Callback', @setNPeriods, ...
    'FontSize', editFontSize);
currentY = currentY - uiHeight - 3*vSpacing;

% --- 3. Sensitivity ---
uicontrol('Parent', tab_helicam, 'Style', 'text', 'String', 'Sensitivity', ...
    'units', 'normalized', 'Position', [0.83 currentY+3*vSpacing 0.06 uiHeight*0.7], ...
    'HorizontalAlignment', 'center', 'FontSize', labelFontSize);
uicontrol('Parent', tab_helicam, 'Style', 'text', 'String', num2str(SensitivityMin), ...
    'units', 'normalized', 'Position', [0.75 currentY 0.03 uiHeight*0.7], ...
    'HorizontalAlignment', 'left', 'FontSize', labelFontSize);
heliHandles.sldSensitivity = uicontrol('Parent', tab_helicam, 'Style', 'slider', ...
    'Min', SensitivityMin, 'Max', SensitivityMax, 'Value', ObjCamera.sensitivity, 'tag', 'sldSensitivity', ...
    'units', 'normalized', 'Position', [0.76 currentY 0.2 uiHeight*0.8], ...
    'Callback', @setSensitivity); 
heliHandles.editSensitivity = uicontrol('Parent', tab_helicam, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.845 currentY-4*vSpacing 0.03 uiHeight*0.8], ...
    'String', sprintf('%.2f', ObjCamera.sensitivity), 'tag', 'editSensitivity', ...
    'Callback', @setSensitivityEdit, 'FontSize', editFontSize);
uicontrol('Parent', tab_helicam, 'Style', 'text', 'String',  num2str(SensitivityMax), ...
    'units', 'normalized', 'Position', [0.97 currentY 0.03 uiHeight*0.7], ...
    'HorizontalAlignment', 'left', 'FontSize', labelFontSize);
% Listener to update edit box from slider value changes (live update)
addlistener(heliHandles.sldSensitivity, 'Value', 'PostSet', @updateSensitivityEditFromSlider);
currentY = currentY - uiHeight - 5*vSpacing;

% --- 4. Coupling Mode ---
heliHandles.bgCoupling = uibuttongroup('Parent', tab_helicam, 'units','normalized', ...
    'Position',[0.75 currentY 0.125 uiHeight*0.8],'tag','coupling',...
    'SelectionChangedFcn', @setCoupling); % No handles needed if only ObjCamera is updated
uicontrol('Parent', heliHandles.bgCoupling, 'Style', 'text', 'String', 'Coupling Mode', ...
    'units', 'normalized', 'Position', [0.01 0.1 0.5 0.8], ...
    'HorizontalAlignment', 'left', 'FontSize', labelFontSize);
heliHandles.rAC = uicontrol(heliHandles.bgCoupling,'Style','radiobutton','units','normalized',...
    'String','AC','FontSize',labelFontSize,'Position',[0.56 0.1 0.2 0.8]);
heliHandles.rDC = uicontrol(heliHandles.bgCoupling,'Style','radiobutton','units','normalized',...
    'String','DC','FontSize',labelFontSize,'Position',[0.8 0.1 0.2 0.8]);

if strcmpi(ObjCamera.coupling,'AC')
   heliHandles.bgCoupling.SelectedObject = heliHandles.rAC;
else
   heliHandles.bgCoupling.SelectedObject = heliHandles.rDC;
end
currentY = currentY - uiHeight - 4*vSpacing;

% --- 5. Modulation Frequency ---

if ~isfield(ObjCamera, 'refFrequency') || ObjCamera.refFrequency < modFreqMin, ObjCamera.refFrequency = modFreqMin; end
if ObjCamera.refFrequency > modFreqMax, ObjCamera.refFrequency = modFreqMax; end

uicontrol('Parent', tab_helicam, 'Style', 'text', 'String', 'Modulation Frequency (kHz)', ...
    'units', 'normalized', 'Position', [0.8 currentY+3*vSpacing 0.12 uiHeight*0.7], ...
    'HorizontalAlignment', 'center', 'FontSize', labelFontSize);
uicontrol('Parent', tab_helicam, 'Style', 'text', 'String', num2str(modFreqMin), ...
    'units', 'normalized', 'Position', [0.75 currentY 0.03 uiHeight*0.7], ...
    'HorizontalAlignment', 'left', 'FontSize', labelFontSize);
heliHandles.sldModFreq = uicontrol('Parent', tab_helicam, 'Style', 'slider', ...
    'Min', modFreqMin, 'Max', modFreqMax, 'Value', ObjCamera.refFrequency, ...
    'tag', 'sldModFreq', 'units', 'normalized', ...
    'Position', [0.76 currentY 0.2 uiHeight*0.8], ...
    'Callback', @setModulationFrequency);
heliHandles.editModFreq = uicontrol('Parent', tab_helicam, 'Style', 'edit', ...
    'units', 'normalized', 'Position', [0.845 currentY-4*vSpacing 0.03 uiHeight*0.8], ...
    'String', num2str(ObjCamera.refFrequency), 'tag', 'editModFreq',...
    'Callback', @setModulationFrequencyEdit, 'FontSize', editFontSize);
uicontrol('Parent', tab_helicam, 'Style', 'text', 'String',  num2str(modFreqMax), ...
    'units', 'normalized', 'Position', [0.97 currentY 0.03 uiHeight*0.7], ...
    'HorizontalAlignment', 'left', 'FontSize', labelFontSize);
% Listener to update edit box from slider value changes (live update)
addlistener(heliHandles.sldModFreq, 'Value', 'PostSet', @updateModFreqEditFromSlider);
currentY = currentY - uiHeight - vSpacing;

% --- 6. SEND Button ---
uicontrol('Parent', tab_helicam, 'Style', 'pushbutton', 'String', 'SEND', ...
    'tag', 'sendToHeliotis', 'units', 'normalized', ...
    'Position', [0.89 0.905 0.055 uiHeight*1.5], 'FontSize', labelFontSize+2, ...
    'FontWeight', 'bold', 'Callback', @SendParamToHeliCam);

% Optional: If you need to access heliHandles from outside this script,
% you could store it, for example, in the tab's UserData or app data.
% set(tab_helicam, 'UserData', heliHandles);

